### PR TITLE
Unicode characters in variable names and for built-in symbols

### PR DESCRIPTION
**Pull request by McEarl**
Allow usage of Unicode characters in variable names. Variables are encoded by the Unicode code pints of their characters, so that they don't cause any problems when exported to external provers. Moreover, built-in symbols like `=>`, `\implies`, `!=`, `\neq`, ... can be replaced by appropriate Unicode characters like `⟹`, `≠`, ... . Using XeLaTeX and the package _unicode-math_, these changes also don't cause any problems when converting a `.ftl.tex` file to PDF.

These changes not only make `.ftl` and `.ftl.tex` more readable, but also can speed up the formalization process if a keyboard layout is used which supports direct input of, e.g.,  greek letters or logical symbols.

**Note:** Unfortunately this pull request includes also the changes made by pull request <https://github.com/naproche/naproche/pull/5>...

### CODE REVIEW

**Comment by makarius** [comment]
"Unicode" opens a can of worms of many problems, accumulated over decades.

Isabelle has its own way to treat mathematical symbols in Isabelle, but it is in conflict with low-level Unicode. So this is unlikely to work within Isabelle/PIDE.

**Comment by PeterKoepke** [comment]
I strongly suggest to stay with good old ASCII, using LaTeX commands for symbols. This is a stable basis for the kind of input that we are expecting from mathematicians and it will cover their typesetting needs. We are a small group that will not be able to quickly adapt our programs if somebody would like another unicode for a similar but slightly different symbol. Or if something changes with unicode or the treatment of unicode in editors or operating systems. So people, alas, should use some more keystrokes but stay within a conservative and compatible coding system.

**Comment by McEarl** [comment]
Maybe we should discuss this topic in one of our meetings. But let me shortly respond to your objections.

* If you change the character encoding in Isabelle/PIDE from UFT-8-Isabelle to UFT-8 then it works fine ;-)
* Sure, ASCII does a good job, but I mean we live in the 21st century, don't we?! For machines ASCII texts are just fine, but for a human they can be horrible to read (and even to write).
* I don't think that LaTeX really covers the mathematicians' typesetting needs. It's just the best typesetting environment we have, which doesn't mean that it cannot be improved. I simply don't want to hammer seven times on my keyboard just to get a single φ out of it. And as XeLaTeX proves, this wish can indeed be fulfilled. So why not take the step from _LaTeX ForTheL_ to something like _XeLaTeX ForTheL_?
* We "will not be able to quickly adapt our programs if somebody would like another unicode for a similar but slightly different symbol": Maybe I didn't understand you correctly, but is there any difference if you replace the word "unicode" by "LaTeX command"? So is this really a Unicode issue?
* Do we really have to care about how Unicode standards etc. change over time? All we need to do is using appropriate Haskell libraries for dealing with Unicode (as we already do), don't we?

So all that remains to me are the technical issues that come with Unicode. But unfortunately I have no idea what they look like...

**Comment by makarius** [comment]
The 21st century is indeed a dark age, where not even "plain text" is well-defined anymore.

I have struggled with the "Unicode Problem" for 10-15 years in Isabelle, and eventually managed to make some (limited) sense of it with Isabelle symbols in Isabelle/Scala/PIDE (which is actually closer to original LaTeX than Unicode).

Whatever is done is this respect needs to work across multiple languages: ML, OCaml, Scala, Java, JavaScript, Haskell. It also needs to work across editors and operating systems.

That is a huge problem complex, and in 10-15 more years it might work again a little bit better.

**Comment by McEarl** [comment]
Just remembered that even in the current version of Naproche Unicode variables are already supported. They just can't be used when it comes to proving since they are not exported properly to the ATP. For example calling Naproche with the `-T` option works fine for
```
Lemma. Let α be a set. Then α is a function.
```
and it outputs:
```
parsing successful
conjecture.
  assume aSet(α).
  aFunction(α).
```

I think we should keep that in mind if Unicode is such a huge problem.

**Comment by anfelor** [comment]
I would be in favor of Unicode symbols: For example, Lean has supported them for many years and mathlib uses them quite extensively. I think it can make mathematical expressions much easier to read. However, Makarius point is true: It can be difficult to interact with Unicode across systems. In particular, I think that most LaTeX distributions can't render the files as they appear in this PR (only XeTeX supported unicode last time I checked). Maybe we could write a parser for the latex macro `\DeclareUnicodeCharacter{codepoint}{latex}` and then replace the codepoint by the latex expression in Naproche? That would also do away with the somewhat verbose translation to FOF that you added in this PR.

@makarius: Can Isabelle/Jedit handle latex using `\usepackage[utf8]{inputenc}` and `\DeclareUnicodeCharacter`?

**Comment by makarius** [comment]
"Unicode" is a big mess and misunderstanding. Initially, it was not even meant to support mathematical typesetting.
I don't want to repeat all the bad jokes about it on a Gitbug discussion thread.

We need to step back from it and ask: What do we actually want to achieve? What is a proper way to do it?

Note that Isabelle2021 has tried to jump on the current LuaLaTeX train, where LaTeX is generally moving now. Maybe that was a bit too early: it has caused some collateral damage on non-mathematical Unicode text. For example, in https://isabelle-dev.sketis.net/rISABELLEbc97bd4c0474 "Weierstraß" is back to "Weierstra{\ss}".

I am glad that "\<alpha>" in Isabelle sources will remain "\<alpha>" for decades to come. And some future software archeologists will manage to understand our ASCII sources even centuries later.

**Comment by PeterKoepke** [comment]
I suggest that we have a discussion about the further develpment of Naproche once the Isabelle - Naproche project with Makarius has started. Personally I am worried about putting Unicode on top of the current treatment of LaTeX, where we do not even have a systematic way of working with the LaTeX backslash ( \ ). As long as we have to resolve more serious issues like a change in parsing mechanisms, possibly another backend, difficulties with ontological checking in complex theories, etc. I would advise against changing features that do work at the moment.

**Comment by McEarl** [comment]
Oh dear, actually I never wanted to start such a big discussion. Just to make my point clear: With this pull request I simply wanted to bridge the gap between the current possibility to use Unicode variables in Naproche (which has been supported by the parser for quite a long time) and the error messages that appear on the ATP's side when such variables are passed to it. Everything else like better readability of source files and so on are just a nice side effects but not the main concern of this pull request.

**Comment by McEarl** [comment]
I've changed this PR such that it now contains only the essential fix of the internal representation of Unicode variables. The following changes have been completely reverted:

* The usage of non-ASCII symbols in the examples
* New built-in non-ASCII characters for logical and structural symbols (e.g. `⟹` or `≠`)
* The underscore fix from PR #5 (don't know why it was part of the branch this PR is based on at all)

So what is left now in this PR is just an improvement of the internal representation of variable names: They are encoded by ASCII strings before being exported to the ATP. So even if a variable name contains a non-ASCII character (which can happen since the parser does not reject non-ASCII characters in variable names) it can be passed to the ATP. Thus this PR can be seen rather as a fix than as providing a new feature. A quick look at the changes of the source code in commit [3217dcd](https://github.com/naproche/naproche/pull/6/commits/3217dcd165a825f6451a771b321ac90d839548e1) should show that it does not give rise to any (new) Unicode conflicts. At least I think so; if it does, just leave a comment :)

---
I know, the commit history is very messy now. Almost every changes have been reverted, but they still appear in the history... Don't be confused by that.

**Pull request closed without merging**
